data_dbt_training:
  target: dev
  outputs:
    dev:
      account: "{{env_var('DBT_ENV_SECRET_ACCOUNT_NAME')}}"
      type: snowflake
      database: "{{env_var('DBT_DB_NAME')}}"
      role: "{{env_var('DBT_ROLE_NAME')}}"
      schema: "{{env_var('DBT_SCHEMA_NAME')}}"
      threads: 4
      user: "{{env_var('DBT_USERNAME')}}"
      password: "{{env_var('DBT_ENV_SECRET_PASSWORD')}}"
      warehouse: "{{env_var('DBT_WH_NAME')}}"
    ci:
      account: "{{env_var('DBT_ENV_SECRET_ACCOUNT_NAME')}}"
      type: snowflake
      database: "{{env_var('DBT_DB_NAME')}}"
      role: "{{env_var('DBT_ROLE_NAME')}}"
      schema: "{{env_var('DBT_SCHEMA_NAME')}}_CI"
      threads: 4
      user: "{{env_var('DBT_USERNAME')}}"
      password: "{{env_var('DBT_ENV_SECRET_PASSWORD')}}"
      warehouse: "{{env_var('DBT_WH_NAME')}}"
    prod:
      account: "{{env_var('DBT_ENV_SECRET_ACCOUNT_NAME')}}"
      type: snowflake
      database: "{{env_var('DBT_DB_NAME_PROD')}}"
      role: "{{env_var('DBT_ROLE_NAME_PROD')}}"
      schema: "{{env_var('DBT_SCHEMA_NAME_PROD')}}"
      threads: 4
      user: "{{env_var('DBT_USERNAME_PROD')}}"
      password: "{{env_var('DBT_ENV_SECRET_PASSWORD')}}"
      warehouse: "{{env_var('DBT_WH_NAME_PROD')}}"
